version: '3.9'

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    container_name: wazuh-certs-generator
    volumes:
      - ../wazuh/config/wazuh_indexer_ssl_certs/:/certificates/
      - ../wazuh/config/certs.yml:/config/certs.yml